#  Workflow for Gitleaks Secrets verification
# https://github.com/Plan-A-Technologies/Secrets-Scanning-Project

name: Check for Leaked Secrets using GitLeaks

on: [pull_request, push, workflow_dispatch]

jobs:
  scan:
    name: GitLeaks Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Added as Organization Secret
