#  Workflow for Gitleaks Secrets verification
# https://github.com/Plan-A-Technologies/Secrets-Scanning-Project

name: Check for Leaked Secrets using GitLeaks

on: [pull_request, push, workflow_dispatch, workflow_call]

jobs:
  scan_for_leaked_secrets:
    uses: Plan-A-Technologies/template-actions/.github/workflows/gitleaks.yml@main
    secrets: inherit
